### PR TITLE
Match the Restore action with behavior of Firefox (Ctrl + Shift + T)

### PR DESCRIPTION
**Pull request by wantora**
* Prevent a window from being restore
* Restore only the tabs of the current window

### CODE REVIEW

**Comment by Robbendebiene** [comment]
Hi and thanks for your pull request. However I prefer this functionality to be optional and I also added this some time ago in my local branch.

**Comment by wantora** [comment]
Should I implement the option?

**Comment by Robbendebiene** [comment]
Since I already did this, there is no need for this anymore.

**Comment by wantora** [comment]
I understand. Thank you!

**Comment by Robbendebiene** [comment]
Nevertheless thanks for your effort :) I plan to add this option in the upcoming version 2.0

**Pull request closed without merging**
