### PR TITLE
Added new action OpenImage

### PR DESCRIPTION
**Pull request by hyagli**

### CODE REVIEW

**Comment by Robbendebiene** [comment]
Thanks!
But `url = data.link.href;` shouldn't it be `url = data.target.src;`?

**Comment by hyagli** [comment]
Hey there,

I removed data.link.href line and shortened code.

**Comment by Robbendebiene** [comment]
Thank you!

**Comment by hyagli** [comment]
You're welcome. Happy to contribute to such a useful addon 🥇

**Pull request merged**
