### PR TITLE
Bug fix #292 about Percent-Encoding

### LINKED ISSUE #292: Save  image save files with % in names
hi
Save image save files with % in names if they are not in english (as i think).
link for example http://joyreactor.cc/post/3484061
op picture saves as KatRaccoon-%D0%9A%D0%BE%D0%BC%D0%B8%D0%BA%D1%81%D1%8B-%D0%BA%D1%83%D1%80%D1%8B-4442270.jpeg
but if save via context menu or ctrl+s it will be saved as KatRaccoon-Комиксы-куры-4442270.jpeg (which is correct and expected behavior)
please fix

win8.1
moz 60.0.1
gest 1.2.2

### PR DESCRIPTION
**Pull request by dkalke**
decoded the URL and spilled the file name

### CODE REVIEW

**Comment by Robbendebiene** [comment]
Thank you for your pull request.

As you already may have noticed there recently were a lot of changes to the master branch. This is because we are getting close to the new Gesturefy 2.0 release. Can you please update your commit/pull request so I can easily merge it? (the filename changed from actions.js to commands.js)

The only thing I would like to change/remove is:
`url = decodeURI(data.target.src);`
Even though it is working I would prefer to pass the encoded string to the browser API instead of the decoded one, just to be on the safe side :)

Either use another variable or write it like this:
`title = decodeURI(data.target.src).split(/(\\|\/)/g).pop();`

**Comment by Robbendebiene** [comment]
To further match the default behaviour you should also only parse the filename from the path. This can be easily accomplished using an URL object. Because image URLs can also look like this: https://dummyimage.com/600x400/000/fff?example=value

```
const pathname = decodeURI(new URL(url).pathname);
title = pathname.split(/(\\|\/)/g).pop();
```

**Comment by dkalke** [comment]
The new Gesturefy 2.0, Great!

I will update this code in the few days.
Thank you for your advice.

**Comment by dkalke** [comment]
Done.
Remove decoded URL and use URL object to get the file name.

**Comment by Robbendebiene** [comment]
Thank you very much :)

**Pull request merged**
