### PR TITLE
Add zh_CN locale, refine strings and more l10n

### PR DESCRIPTION
**Pull request by yfdyh000**

### CODE REVIEW

**Comment by Robbendebiene** [comment]
Thank you very much! I'll try to add most of it before I submit the new version to mozilla. :)

**Comment by Robbendebiene** [comment]
Just 2 little things:
1) Can you please change the first commit (de750890fd21732a4ed7380084d67a2e154034ab), I would like to add your language file, but I'm not content with all the changes in src/_locales/en/messages.json.
2) I would only merge these commits: de750890fd21732a4ed7380084d67a2e154034ab and b77bd8f359516cdfe0146ebcef064f26c532bafc because there is a slightly better way for the last one.

**Comment by Robbendebiene** [comment]
Great! Just a last question. Are you sure about the folder name? I would have named it just "zh", but I may be wrong :)

**Comment by yfdyh000** [comment]
It should be `zh_CN`, `zh_TW` is another common variant.

**Comment by Robbendebiene** [comment]
Alright.
To talk about my "slightly better solution".. I thought adding it directly to the css would be neat like this:
```
.toggleButton + label:after {
  content: "__MSG_toggleButtonOff__";
}

.toggleButton:checked + label:after {
  content: "__MSG_toggleButtonOn__";
}
```
And it's working fine, except for the Chinese language. Do you know if I have to set a special encoding for this? I thought adding `@charset "UTF-8";` to the css file would do the trick, but turns out it does not.

**Comment by yfdyh000** [comment]
It is a great idea. I don't know why it's like this, but a valid hack: got encoded characters for CSS from https://r12a.github.io/apps/conversion/. `"\\5F00"` (on) and `"\\5173"` (off) working.

**Comment by Robbendebiene** [comment]
Yeah, perfect.

**Pull request merged**
