### PR TITLE
Changed "Blacklist" to "Blocklist" (inclusive language)

### PR DESCRIPTION
**Pull request by ledeniz**
Hi there,

Since I use Gesturefy extensively I thought it'd be nice to give something back, even if it's just a very small PR like this.
I hope this does not cause any technical difficulties :)

Some time ago I stumbled upon the term "blocklist" as an replacement for "blacklist", which I think is a really elegant switch to a more inclusive term. So I thought maybe it'd be a good idea to include this term in Gesturefy.

I splitted the changes of the two different notations in two seperate commits.

EDIT: I just found a typo in the german translation and added that as well.

### CODE REVIEW

**Comment by Robbendebiene** [comment]
Hi, thanks for the pull request!

This concern has been raised about two years ago on [crowdin](https://crowdin.com/project/gesturefy). Back then I decided not to change the term, or at least I left it open for further discussion. Here is what I wrote:

> Thanks for bringing up this point, because it is an important topic. During the last days I read about the origin of the term "blacklist", the black-and-white dualism and asked some friends for their opinion. My conclusion so far is that the associations “good” for white and “bad” for black do not originate from racism (of course it was highly abused later on). Instead the origin seems to lie in our human nature. From the past and until now, day or light (white) is often associated with good and peace, where night or darkness (black) is often considered as dangerous and a place of evil. This seems reasonable to me since humans are diurnal animals and can't see very good at night. There is also an interesting story about how the term “blacklist” (perhaps) came up, which is described here: https://www.quora.com/Is-the-term-blacklist-racist
> While I totally can understand that people who identify themselves as black may feel uncomfortable with the term, it was never meant to harm or to discriminate them. I think there can be found a lot of similar things for other colors. For example the color red which has positive associations (like love) but also negative associations (like danger, blood and fire). When we use red as a warning symbol it's not related to people with a red skin color and I guess also no one thinks that. Its origin is located in evolution, since red is often used in nature to signify danger. Another example for the color “white” would be the term “Whitewashing”.
> I’m all for removing discriminating words from our daily vocabulary, so I’ll leave this open for further discussion. At the end changing the word is not a big deal, it’s just that the alternatives like “blocklist” etc. aren’t as clearly as the term blacklist is, since it’s widely established.

I'm still not convinced that replacing words containing the color black with a negative meaning is the right way to fight discrimination (as long as they are not invented or used for discrimination). However it's a minor change and it doesn't have any real drawbacks, so I'm going for it.

There are just some little problems with your PR.

1. Gesturefy's language strings are managed through [crowdin](https://crowdin.com/project/gesturefy). It's an excellent site for collaborative translating. Because of that making changes to strings on Github can cause problems, wherefore I try to avoid that.
2. Since the config/setting string also changes, it will cause current users to lose their blacklist entries. Because of that I need to implement a little function that moves them to the new term.
3. I think there are alternative words which may not be as short as blocklist, but better describe what this list is actually doing. Since it isn't really blocking anything. I came across these alternatives [here](https://english.stackexchange.com/questions/51088/alternative-term-to-blacklist-and-whitelist).

- deny list
- **exclude List**
- disable list
- **exclusions**

_(marked my current favorites bold)_

I would suggest we proceed the following way. Once we agreed on a term you only change the following files:

- Readme.mdn
- only `_locales/en/messages.json` (because crowdin will adjust the other files)
- everything in the` src/views/` directory

Then I will do the remaining code changes + the necessary function that transitions old blacklist entries to the new term.

@ledeniz & @Itchiii Which term do you prefer or do you have any other ideas?

> EDIT: I just found a typo in the german translation and added that as well.

Thanks for that, I fixed it on crowdin.

**Comment by Robbendebiene** [comment]
**Reminder to myself: The Wiki and URL should also be changed: https://github.com/Robbendebiene/Gesturefy/wiki**

**Comment by ledeniz** [comment]
Thanks for your concerns! And sorry, I didn't know about the crowdin integration. 

I think the effect of inclusive language is really hard to measure, but since it doesn't really hurt to change it I would say it's the safer bet.
> @ledeniz & @Itchiii Which term do you prefer or do you have any other ideas?
I think 'exclusions' is a good replacement for this case.

**Comment by Itchiii** [comment]
I'm of the opinion that it is right and important to research word origins and also to analyze today's associations and, if necessary, to adapt accordingly when people feel discriminated against. As Robbendebiene already wrote, by the change, we have no disadvantage. But I think it will increase the awareness that there are problematic terms (no matter if "blacklist" is one or not). 

> @ledeniz & @Itchiii Which term do you prefer or do you have any other ideas?
I am also for "exclusions"

**Comment by Robbendebiene** [comment]
All right then we go with **Exclusions/exclusions**.

**Comment by Robbendebiene** [comment]
@ledeniz I just wanted to ask if you still want to work on this pull request?

> I would suggest we proceed the following way. Once we agreed on a term you only change the following files:
> 
> - Readme.mdn
>  - only _locales/en/messages.json (because crowdin will adjust the other files)
>   -  everything in the src/views/ directory
> 
> Then I will do the remaining code changes + the necessary function that transitions old blacklist entries to the new term.

**Comment by ledeniz** [comment]
@Robbendebiene done :) (if I didn't mess up.. please check)

**Comment by Robbendebiene** [comment]
Uhm you still named it "Blocklist" instead of "Exclusions/exclusions" also you don't need to correct the typo in  `src/_locales/de/messages.json`  anymore it's already done on Crowdin. Other than that it looks good :)

**Comment by ledeniz** [comment]
Hmm I tried to revert my initial changes and only change the files you listed, but I don't think I succeeded.. I'm not sure if I can complete this cleanly to be honest, I'm very sorry

**Comment by Robbendebiene** [comment]
@ledeniz Thanks for your effort. This change is now in [Gesturefy 3.1.0](https://github.com/Robbendebiene/Gesturefy/releases/tag/v3.1.0)

**Pull request closed without merging**
