### PR TITLE
added 4 new actions

### PR DESCRIPTION
**Pull request by hyagli**
- ImageToCurrentTab
- ImageToBackgroundTab
- SaveImageAs
- SaveImageNow

### CODE REVIEW

**Comment by Robbendebiene** [comment]
Hey, thanks for your pull request. (interesting that you understood my source code so quickly :D)

I already added SaveImage/SaveImageNow (I combined it to one gesture with an option and it should be more solid than yours).
I would rename "ImageToCurrentTab" to "OpenImage" because there already is an action which does the same for links/urls which is also named "Open.."
I'm not sure if I would rather like the "ImageToBackgroundTab" as an option for the "ImageToTab" gesture as I did for "SearchSeletedText".
Most importantly, please commit directly to the master branch, because the crowdin branch is used by  https://crowdin.com/project/gesturefy BUT you should wate untill I uploaded my new actions (because of merge conflicts and because I changed a little bit in the bacjground.js too). I will inform you as soon as I commited my changes.

Thanks

**Comment by Robbendebiene** [comment]
I uploaded my new actions.

**Comment by hyagli** [comment]
Hi Rob,

Thanks for the new actions.

> I'm not sure if I would rather like the "ImageToBackgroundTab" as an option for the "ImageToTab" gesture as I did for "SearchSeletedText".

I think there should be two actions:
- Open image in new tab (with two options: background tab, foreground tab)
- View image in current tab

**Comment by Robbendebiene** [comment]
>     Open image in new tab (with two options: background tab, foreground tab)
>     View image in current tab

Yep :)
If you still wish to contribute be aware that "view image" should open a new tab if the tab is pinned (like open homepage or open link does)

**Comment by Jens1948** [comment]
Hi, i would really appreciate if you could add an action to switch the bookmark tree on the left on and off.
Thx in advance!!!
Jens

**Comment by hyagli** [comment]
Hi Jens1948,

Please make a request in the issues section. This place is for the code changes.

**Comment by Jens1948** [comment]
Ok, sorry - i am a newby...

**Comment by Robbendebiene** [comment]
Since you made 2 new pull requests, I'm closing this one :)

**Pull request closed without merging**
