### PR TITLE
Implement improved Referer handling

### PR DESCRIPTION
**Pull request by leonard84**
Fix for #434, I haven't looked into how to test an extension, so it is untested.

### CODE REVIEW

**Comment by leonard84** [comment]
Ah, I misunderstood, I thought it should only send the origin on downgrade, my bad. If you can tell me how to easily test a local extension I can test it. Otherwise, I would just say please release a new version using your implementation ;)

**Comment by Robbendebiene** [comment]
No problem :)

>  If you can tell me how to easily test a local extension I can test it. Otherwise, I would just say please release a new version using your implementation ;)

Testing is actually quite easy:
1. pull the branch
2. open about:debugging#/runtime/this-firefox in Firefox and click the "load temporary add-on" button
3. select the manifest.json from the branch

That's it :)

It would be nice if you could update your pull request if the code fixes your problem.

**Comment by leonard84** [comment]
@Robbendebiene I've tested the new code and it works, I've also pushed the new changes.

**Comment by Robbendebiene** [comment]
Thanks!

**Pull request merged**
