### PR TITLE
Update translations in messages.json

### PR DESCRIPTION
**Pull request by stmr**
Updated translations, everything should be translated and hyphenation should be well :D

### CODE REVIEW

**Comment by Robbendebiene** [comment]
Thank you very much :)

**Comment by stmr** [comment]
Did I do it the right way? :D My first git pull request in somebody elses project

**Comment by Robbendebiene** [comment]
It went flawless :) The only concern I have is, that the czech words for "on" and "off" are quite long and therefore overflow the button.

**Comment by stmr** [comment]
Yeah those are some long words, unfortunately we don't have shorter ones :D Let's keep On Off then

**Pull request merged**
