### PR TITLE
Added a new setting for ImageToTab

### PR DESCRIPTION
**Pull request by hyagli**
The setting name is ImageToTabBackground

### CODE REVIEW

**Comment by Robbendebiene** [comment]
Nice. Can you please rename the settings so they are consitent with the one from `FocusSearchResult`.
So for example: `focusImageToTab` instead of `imageToTabBackground` of course this would require a boolean change in the config and in the code as well.

**Comment by hyagli** [comment]
Done renaming.

**Comment by Robbendebiene** [comment]
Almost perfect :)
Since this is the negation of what it was before "focusImageToTab" should be true by default.

**Comment by hyagli** [comment]
I left it false because I prefer the image to open in background 😄 
Changed the default to true now.

**Comment by Robbendebiene** [comment]
Yeah, that would be a legitimate discussion, but since some people already use the old functionality which only supported opening the image in a foreground tab, I would keep it :)

**Comment by Robbendebiene** [comment]
Oh, and Thank you again!

**Comment by hyagli** [comment]
👍

**Pull request merged**
